import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  // Auth — login / register UI + API handlers
  route("login",    "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("api/auth/google",          "routes/api.auth.google.tsx"),
  route("api/auth/google/callback", "routes/api.auth.google.callback.tsx"),
  route("api/auth/login",           "routes/api.auth.login.tsx"),
  route("api/auth/logout",          "routes/api.auth.logout.tsx"),
  route("api/auth/me",              "routes/api.auth.me.tsx"),
  route("api/auth/register",        "routes/api.auth.register.tsx"),
  // Internal API proxy routes (deliberation + evaluation)
  route("api/deliberate", "routes/api.deliberate.tsx"),
  route("api/evaluate",   "routes/api.evaluate.tsx"),
  // Setup (first launch)
  route("setup", "routes/setup.tsx"),
  // Marketing pages — wrapped with Navbar + Footer
  layout("routes/marketing-layout.tsx", [
    index("routes/landing.tsx"),
    route("pricing", "routes/pricing.tsx"),
    route("about", "routes/about.tsx"),
    route("blog", "routes/blog.tsx"),
    route("careers", "routes/careers.tsx"),
    route("contact", "routes/contact.tsx"),
    route("llm-leaderboard", "routes/llm-leaderboard.tsx"),
    route("infra-calculator", "routes/infra-calculator.tsx"),
    route("status", "routes/status.tsx"),
    route("product/council", "routes/product.council.tsx"),
    route("product/knowledge", "routes/product.knowledge.tsx"),
    route("product/workflows", "routes/product.workflows.tsx"),
    route("product/archetypes", "routes/product.archetypes.tsx"),
    route("product/connectors", "routes/product.connectors.tsx"),
    route("product/developer-platform", "routes/product.developer-platform.tsx"),
    route("product/deliberation-modes", "routes/product.deliberation-modes.tsx"),
    route("product/desktop-app", "routes/product.desktop-app.tsx"),
  ]),
  // App pages (sidebar layout handled by root.tsx)
  route("dashboard", "routes/home.tsx"),
  route("chat", "routes/chat.tsx"),
  route("chat/:id", "routes/chat-detail.tsx"),
  route("settings", "routes/settings.tsx"),
  route("profile", "routes/profile.tsx"),
  route("language-models", "routes/language-models.tsx"),
  route("workflows", "routes/workflows.tsx"),
  route("prompts", "routes/prompts.tsx"),
  route("knowledge-bases", "routes/knowledge-bases.tsx"),
  route("marketplace", "routes/marketplace.tsx"),
  route("archetypes", "routes/archetypes.tsx"),
  route("memory", "routes/memory.tsx"),
  route("skills", "routes/skills.tsx"),
  route("repos", "routes/repos.tsx"),
  route("evaluation", "routes/evaluation.tsx"),
  route("projects", "routes/projects.tsx"),
  route("build", "routes/build.tsx"),
  route("phantom", "routes/phantom.tsx"),
  route("god-mode", "routes/god-mode.tsx"),
  route("ultraplinian", "routes/ultraplinian.tsx"),
  route("parseltongue", "routes/parseltongue.tsx"),
  route("autotune", "routes/autotune.tsx"),
  route("stm", "routes/stm.tsx"),
  route("deep-research", "routes/deep-research.tsx"),
  route("image-gen", "routes/image-gen.tsx"),
  route("connectors/onboarding", "routes/connectors-onboarding.tsx"),
  route("connectors/sync", "routes/connectors-sync.tsx"),
  route("contacts", "routes/contacts.tsx"),
  route("admin/users", "routes/admin-users.tsx"),
  route("admin/analytics", "routes/admin-analytics.tsx"),
  route("admin/system", "routes/admin-system.tsx"),
  route("admin/audit", "routes/admin-audit.tsx"),
  route("admin/traces", "routes/admin-traces.tsx"),
  route("ab-compare", "routes/ab-compare.tsx"),
  route("fine-tune", "routes/fine-tune.tsx"),
  route("knowledge-graph", "routes/knowledge-graph.tsx"),
  route("simulation", "routes/simulation.tsx"),
  route("billing", "routes/billing.tsx"),
  route("web-search", "routes/web-search.tsx"),
  route("rooms", "routes/rooms.tsx"),
  route("sandbox", "routes/sandbox.tsx"),
  route("agents", "routes/agents.tsx"),
  route("api-tokens", "routes/api-tokens.tsx"),
  route("admin/feature-flags", "routes/admin-feature-flags.tsx"),
  route("standard-answers", "routes/standard-answers.tsx"),
  route("admin/feedback", "routes/admin-feedback.tsx"),
  route("scrape", "routes/scrape.tsx"),
  route("quality", "routes/quality.tsx"),
  route("image-transform", "routes/image-transform.tsx"),
  route("costs", "routes/costs.tsx"),
  route("moderation", "routes/moderation.tsx"),
  route("semantic-cache", "routes/semantic-cache.tsx"),
  route("fallback-chains", "routes/fallback-chains.tsx"),
  route("extraction", "routes/extraction.tsx"),
  route("echo-chamber", "routes/echo-chamber.tsx"),
  route("council-checkpoints", "routes/council-checkpoints.tsx"),
  route("reasoning", "routes/reasoning.tsx"),
  route("rss", "routes/rss.tsx"),
  route("craft", "routes/craft.tsx"),
  route("video-transcript", "routes/video-transcript.tsx"),
  route("task-routing", "routes/task-routing.tsx"),
  route("interrupt-resume", "routes/interrupt-resume.tsx"),
  route("blind-council", "routes/blind-council.tsx"),
  route("what-if", "routes/what-if.tsx"),
  route("verifiable", "routes/verifiable.tsx"),
  route("honesty", "routes/honesty.tsx"),
  route("sop", "routes/sop.tsx"),
  route("prompt-filter", "routes/prompt-filter.tsx"),
  route("member-evolution", "routes/member-evolution.tsx"),
  route("negation", "routes/negation.tsx"),
  route("cross-memory", "routes/cross-memory.tsx"),
  route("verbosity", "routes/verbosity.tsx"),
  route("token-conservation", "routes/token-conservation.tsx"),
  route("specialisation", "routes/specialisation.tsx"),
  route("skill-selection", "routes/skill-selection.tsx"),
  route("codegen", "routes/codegen.tsx"),
  route("ghoststack", "routes/ghoststack.tsx"),
] satisfies RouteConfig;
