// SPDX-License-Identifier: Apache-2.0
import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("setup", "routes/setup.tsx"),
  layout("routes/marketing-layout.tsx", [
    index("routes/landing.tsx"),
    route("status", "routes/status.tsx"),
  ]),
  // App pages (sidebar layout handled by root.tsx)
  route("dashboard", "routes/home.tsx"),
  route("chat", "routes/chat.tsx", { id: "chat" }),
  route("chat/:id", "routes/chat.tsx", { id: "chat-thread" }),
  route("live/:id", "routes/live.tsx"),
  route("discussion", "routes/discussion.tsx"),
  route("archetypes", "routes/archetypes.tsx"),
  route("org", "routes/org.tsx"),
  route("projects", "routes/projects.tsx"),
  route("workspaces", "routes/workspaces.tsx"),
  route("invitations/:token", "routes/invitations.tsx"),
  route("workflows", "routes/workflows.tsx"),
  route("skills", "routes/skills.tsx"),
  route("prompts", "routes/prompts.tsx"),
  route("marketplace", "routes/marketplace.tsx"),
  route("knowledge-bases", "routes/knowledge-bases.tsx"),
  route("memory", "routes/memory.tsx"),
  route("markets", "routes/markets.tsx"),
  route("knowledge-graph", "routes/knowledge-graph.tsx"),
  route("standard-answers", "routes/standard-answers.tsx"),
  route("search", "routes/search.tsx"),
  route("deep-research", "routes/deep-research.tsx"),
  route("playground/compare", "routes/playground-compare.tsx"),
  route("sandbox", "routes/sandbox.tsx"),
  route("terminals", "routes/terminals.tsx"),
  route("weather", "routes/weather.tsx"),
  route("drive", "routes/drive.tsx"),
  route("connectors/onboarding", "routes/connectors-onboarding.tsx"),
  route("connectors/sync", "routes/connectors-sync.tsx"),
  route("settings", "routes/settings.tsx"),
  route("profile", "routes/profile.tsx"),
  route("provider-keys", "routes/provider-keys.tsx"),
  route("api-tokens", "routes/api-tokens.tsx"),
  route("mcp-servers", "routes/mcp-servers.tsx"),
  route("costs", "routes/costs.tsx"),
  route("admin/users", "routes/admin-users.tsx"),
  route("admin/analytics", "routes/admin-analytics.tsx"),
  route("admin/system", "routes/admin-system.tsx"),
  route("admin/audit", "routes/admin-audit.tsx"),
  route("admin/traces", "routes/admin-traces.tsx"),
  route("admin/feature-flags", "routes/admin-feature-flags.tsx"),
  route("admin/feedback", "routes/admin-feedback.tsx"),
  route("moderation", "routes/moderation.tsx"),
  route("gateway", "routes/gateway.tsx"),
] satisfies RouteConfig;
