-- SPDX-License-Identifier: Apache-2.0
-- M3 bootstrap migration — creates all nexus core tables.
-- Generated by: drizzle-kit generate (manual seed for initial commit)
-- Run after Judica's 62 Drizzle schemas are migrated (those run first via db:migrate in @nexus/db)

-- ─── ingested_events ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "ingested_events" (
  "id"               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "source"           text NOT NULL,
  "event_type"       text NOT NULL,
  "payload"          jsonb NOT NULL,
  "metadata"         jsonb,
  "idempotency_key"  text,
  "created_at"       timestamptz NOT NULL DEFAULT now(),
  "processed_at"     timestamptz
);

CREATE INDEX IF NOT EXISTS "ingested_events_source_idx"      ON "ingested_events" ("source");
CREATE INDEX IF NOT EXISTS "ingested_events_event_type_idx"  ON "ingested_events" ("event_type");
CREATE INDEX IF NOT EXISTS "ingested_events_created_at_idx"  ON "ingested_events" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "ingested_events_idempotency_key_udx"
  ON "ingested_events" ("idempotency_key")
  WHERE "idempotency_key" IS NOT NULL;

-- ─── signals ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "signals" (
  "id"               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "signal_type"      text NOT NULL,
  "source_event_ids" uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
  "summary"          text NOT NULL,
  "priority"         text NOT NULL DEFAULT 'medium'
                       CHECK ("priority" IN ('low','medium','high','critical')),
  "metadata"         jsonb,
  "created_at"       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "signals_signal_type_idx" ON "signals" ("signal_type");
CREATE INDEX IF NOT EXISTS "signals_priority_idx"    ON "signals" ("priority");
CREATE INDEX IF NOT EXISTS "signals_created_at_idx"  ON "signals" ("created_at");

-- ─── verdicts ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "verdicts" (
  "id"          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "signal_id"   uuid NOT NULL REFERENCES "signals"("id") ON DELETE CASCADE,
  "decision"    text NOT NULL CHECK ("decision" IN ('approve','reject','defer','escalate')),
  "confidence"  real NOT NULL,
  "rationale"   text NOT NULL,
  "dissents"    text[] NOT NULL DEFAULT ARRAY[]::text[],
  "actions"     jsonb,
  "cost_usd"    numeric(10,6),
  "created_at"  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "verdicts_signal_id_idx"  ON "verdicts" ("signal_id");
CREATE INDEX IF NOT EXISTS "verdicts_decision_idx"   ON "verdicts" ("decision");
CREATE INDEX IF NOT EXISTS "verdicts_created_at_idx" ON "verdicts" ("created_at");

-- ─── council_transcripts ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "council_transcripts" (
  "id"          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "verdict_id"  uuid NOT NULL UNIQUE REFERENCES "verdicts"("id") ON DELETE CASCADE,
  "turns"       jsonb NOT NULL DEFAULT '[]'::jsonb,
  "created_at"  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "council_transcripts_verdict_id_idx"  ON "council_transcripts" ("verdict_id");
CREATE INDEX IF NOT EXISTS "council_transcripts_created_at_idx"  ON "council_transcripts" ("created_at");

-- ─── runtime_tasks ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "runtime_tasks" (
  "id"               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "type"             text NOT NULL,
  "payload"          jsonb NOT NULL,
  "status"           text NOT NULL DEFAULT 'queued'
                       CHECK ("status" IN ('queued','running','completed','failed','cancelled','awaiting_approval')),
  "priority"         text NOT NULL DEFAULT 'medium'
                       CHECK ("priority" IN ('low','medium','high')),
  "verdict_id"       uuid REFERENCES "verdicts"("id") ON DELETE SET NULL,
  "idempotency_key"  text,
  "error"            text,
  "result"           jsonb,
  "created_at"       timestamptz NOT NULL DEFAULT now(),
  "started_at"       timestamptz,
  "completed_at"     timestamptz
);

CREATE INDEX IF NOT EXISTS "runtime_tasks_status_idx"     ON "runtime_tasks" ("status");
CREATE INDEX IF NOT EXISTS "runtime_tasks_priority_idx"   ON "runtime_tasks" ("priority");
CREATE INDEX IF NOT EXISTS "runtime_tasks_type_idx"       ON "runtime_tasks" ("type");
CREATE INDEX IF NOT EXISTS "runtime_tasks_verdict_id_idx" ON "runtime_tasks" ("verdict_id");
CREATE INDEX IF NOT EXISTS "runtime_tasks_created_at_idx" ON "runtime_tasks" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "runtime_tasks_idempotency_key_udx"
  ON "runtime_tasks" ("idempotency_key")
  WHERE "idempotency_key" IS NOT NULL;

-- ─── approval_requests ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "approval_requests" (
  "id"           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "entity_type"  text NOT NULL,
  "entity_id"    uuid NOT NULL,
  "action"       text NOT NULL,
  "requestor"    text NOT NULL,
  "status"       text NOT NULL DEFAULT 'pending'
                   CHECK ("status" IN ('pending','approved','rejected','expired')),
  "resolution"   text CHECK ("resolution" IN ('approved','rejected')),
  "resolved_by"  text,
  "reason"       text,
  "context"      jsonb,
  "created_at"   timestamptz NOT NULL DEFAULT now(),
  "resolved_at"  timestamptz,
  "expires_at"   timestamptz
);

CREATE INDEX IF NOT EXISTS "approval_requests_entity_idx"     ON "approval_requests" ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "approval_requests_status_idx"     ON "approval_requests" ("status");
CREATE INDEX IF NOT EXISTS "approval_requests_requestor_idx"  ON "approval_requests" ("requestor");
CREATE INDEX IF NOT EXISTS "approval_requests_created_at_idx" ON "approval_requests" ("created_at");
CREATE INDEX IF NOT EXISTS "approval_requests_expires_at_idx" ON "approval_requests" ("expires_at");

-- ─── audit_log (append-only) ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "audit_log" (
  "id"            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "sequence"      bigint NOT NULL,
  "entity_type"   text NOT NULL,
  "entity_id"     uuid NOT NULL,
  "action"        text NOT NULL,
  "actor"         text NOT NULL,
  "payload"       jsonb,
  "payload_hash"  text NOT NULL,
  "chain_hash"    text NOT NULL,
  "created_at"    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "audit_log_sequence_udx"   ON "audit_log" ("sequence");
CREATE INDEX IF NOT EXISTS "audit_log_entity_idx"            ON "audit_log" ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_log_action_idx"            ON "audit_log" ("action");
CREATE INDEX IF NOT EXISTS "audit_log_actor_idx"             ON "audit_log" ("actor");
CREATE INDEX IF NOT EXISTS "audit_log_created_at_idx"        ON "audit_log" ("created_at");

-- Append-only enforcement: prevent UPDATE and DELETE on audit_log
CREATE OR REPLACE FUNCTION nexus_audit_log_immutable()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION
    'audit_log is append-only. UPDATE and DELETE are not permitted (ADR-0010). '
    'Attempted operation: %', TG_OP;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS audit_log_no_update ON "audit_log";
CREATE TRIGGER audit_log_no_update
  BEFORE UPDATE ON "audit_log"
  FOR EACH ROW EXECUTE FUNCTION nexus_audit_log_immutable();

DROP TRIGGER IF EXISTS audit_log_no_delete ON "audit_log";
CREATE TRIGGER audit_log_no_delete
  BEFORE DELETE ON "audit_log"
  FOR EACH ROW EXECUTE FUNCTION nexus_audit_log_immutable();

-- ─── Drizzle migrations bookkeeping ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "nexus_drizzle_migrations" (
  id        serial PRIMARY KEY,
  hash      text NOT NULL,
  created_at bigint
);
