// SPDX-License-Identifier: Apache-2.0
/**
 * skill-runner tests — the skills → runtime execution bridge.
 *
 * Covers: system-prompt composition from skill records (with deduped code
 * bodies), the run_skill_code tool executing skill code through the sandbox
 * (injected runner), {{param}} substitution, and the fail → recover → continue
 * contract (failed runs surface as recoverable errors, never throws).
 */

import { describe, it, expect } from "vitest";
import type { Runner, RunnerResult } from "@nexus/sandbox";

import {
  composeSkillSystemPrompt,
  executeSkillsOnce,
  makeRunSkillCodeTool,
  mergeSkillCodeBodies,
  skillLanguageToSandbox,
  substituteParams,
  withOutputStyle,
  type SkillExecutionRecorder,
  type SkillRecord,
} from "../../src/lib/skill-runner.js";

function fakeRunner(result: Partial<RunnerResult>): Runner {
  return async () => ({
    stdout: "",
    stderr: "",
    exitCode: 0,
    timedOut: false,
    ...result,
  });
}

const PYTHON_SKILL: SkillRecord = {
  id: "skill-1",
  name: "report-writer",
  description: "Writes a markdown report to report.md",
  language: "Python",
  code: [
    "import pathlib",
    "pathlib.Path('report.md').write_text('# Report\\nGenerated by skill.')",
    "print('report written')",
  ].join("\n"),
};

const TS_SKILL: SkillRecord = {
  id: "skill-2",
  name: "counter",
  language: "TypeScript",
  code: "const n = 2 + 2;\nconsole.log('sum=' + n);",
};

describe("skillLanguageToSandbox", () => {
  it("maps language labels to sandbox runtimes", () => {
    expect(skillLanguageToSandbox("Python")).toBe("python");
    expect(skillLanguageToSandbox("typescript")).toBe("typescript");
    expect(skillLanguageToSandbox("JavaScript")).toBe("javascript");
    expect(skillLanguageToSandbox("bash")).toBe("bash");
  });

  it("returns undefined for unsupported languages", () => {
    expect(skillLanguageToSandbox("Go")).toBeUndefined();
    expect(skillLanguageToSandbox(undefined)).toBeUndefined();
    expect(skillLanguageToSandbox("")).toBeUndefined();
  });
});

describe("substituteParams", () => {
  it("replaces {{name}} placeholders from runtime params", () => {
    const code = "print('hello {{name}}, you are {{age}}')";
    expect(substituteParams(code, { name: "Nexus", age: 7 })).toBe(
      "print('hello Nexus, you are 7')",
    );
  });

  it("leaves unknown placeholders untouched", () => {
    expect(substituteParams("{{missing}}", { other: 1 })).toBe("{{missing}}");
    expect(substituteParams("plain", undefined)).toBe("plain");
  });
});

describe("mergeSkillCodeBodies", () => {
  it("dedupes shared imports and sections per skill", () => {
    const a: SkillRecord = { id: "a", name: "A", code: "import pathlib\nx = 1" };
    const b: SkillRecord = { id: "b", name: "B", code: "import pathlib\ny = 2" };
    const merged = mergeSkillCodeBodies([a, b]);
    expect(merged).toContain("// ── A (a) ──");
    expect(merged).toContain("// ── B (b) ──");
    // Shared import appears exactly once.
    expect(merged.split("import pathlib").length - 1).toBe(1);
  });
});

describe("composeSkillSystemPrompt", () => {
  it("includes skill names, descriptions, ids, and the goal", () => {
    const prompt = composeSkillSystemPrompt([PYTHON_SKILL], "Write the report");
    expect(prompt).toContain("## Skill: report-writer (Python)");
    expect(prompt).toContain("Writes a markdown report to report.md");
    expect(prompt).toContain("id: skill-1");
    expect(prompt).toContain("## Goal\nWrite the report");
  });

  it("directs the agent to execute code and recover from failures — not restate it", () => {
    const prompt = composeSkillSystemPrompt([PYTHON_SKILL], "go");
    expect(prompt).toContain("run_skill_code");
    expect(prompt).toContain("RECOVER");
    // The agent is told to RUN the code, not paraphrase the skill.
    expect(prompt).toContain("never just\nrestate instructions");
  });

  it("embeds real pre-execution results when the harness ran the skills", () => {
    const prompt = composeSkillSystemPrompt([PYTHON_SKILL], "go", [
      {
        skillId: "skill-1",
        skillName: "report-writer",
        language: "python",
        ok: true,
        exitCode: 0,
        timedOut: false,
        durationMs: 12,
        output: "=== stdout ===\nreport written\n",
      },
    ]);
    expect(prompt).toContain("## Pre-execution results");
    expect(prompt).toContain("report-writer (python): OK — exit 0, 12ms");
    expect(prompt).toContain("report written");
  });

  it("marks failed pre-executions as recovery tasks", () => {
    const prompt = composeSkillSystemPrompt([PYTHON_SKILL], "go", [
      {
        skillId: "skill-1",
        skillName: "report-writer",
        language: "python",
        ok: false,
        exitCode: 1,
        timedOut: false,
        durationMs: 9,
        output: "=== stderr ===\nTraceback: boom",
        error: "exit 1",
      },
    ]);
    expect(prompt).toContain("report-writer (python): FAILED — exit 1, 9ms");
    expect(prompt).toContain("Never report success on a failed run");
  });
});

describe("withOutputStyle", () => {
  it("injects the ponytail style (caveman-ponytail) and stays idempotent", () => {
    const base = "You are a mission agent.";
    const styled = withOutputStyle(base, "ponytail");
    expect(styled).toContain("best code is the code never written");
    expect(styled).toContain("Be terse");
    expect(styled.startsWith(base)).toBe(true);
    expect(withOutputStyle(styled, "ponytail")).toBe(styled);
  });

  it("maps caveman to the caveman-output style and normal to a no-op", () => {
    expect(withOutputStyle("base", "caveman")).toContain("Reply in minimal words");
    expect(withOutputStyle("base", "terse")).toContain("Be terse");
    expect(withOutputStyle("base", "normal")).toBe("base");
  });
});

describe("executeSkillsOnce", () => {
  it("runs every skill's code deterministically and returns real outcomes", async () => {
    const results = await executeSkillsOnce([PYTHON_SKILL, TS_SKILL], {
      runner: fakeRunner({ stdout: "ran\n", exitCode: 0 }),
    });
    expect(results).toHaveLength(2);
    const py = results[0]!;
    expect(py.ok).toBe(true);
    expect(py.skillName).toBe("report-writer");
    expect(py.language).toBe("python");
    expect(py.output).toContain("ran");
    const ts = results[1]!;
    expect(ts.language).toBe("typescript");
    expect(ts.ok).toBe(true);
  });

  it("returns failed runs as results (never throws) — recovery input for the agent", async () => {
    const results = await executeSkillsOnce([PYTHON_SKILL], {
      runner: fakeRunner({ stderr: "Traceback: boom", exitCode: 2 }),
    });
    expect(results[0]!.ok).toBe(false);
    expect(results[0]!.exitCode).toBe(2);
    expect(results[0]!.output).toContain("Traceback: boom");
  });

  it("flags unsupported languages honestly", async () => {
    const results = await executeSkillsOnce(
      [{ id: "go1", name: "gopher", language: "Go", code: "package main" }],
      { runner: fakeRunner({}) },
    );
    expect(results[0]!.ok).toBe(false);
    expect(results[0]!.language).toBe("unsupported");
    expect(results[0]!.error).toContain("unsupported language");
  });
});

describe("makeRunSkillCodeTool", () => {
  it("executes the skill's code via the sandbox and returns output", async () => {
    const tool = makeRunSkillCodeTool([PYTHON_SKILL], {
      runner: fakeRunner({ stdout: "report written\n", exitCode: 0 }),
    });
    const result = (await tool.handler({ skill_id: "skill-1" })) as Record<string, unknown>;
    expect(result.ok).toBe(true);
    expect(result.skill).toBe("report-writer");
    expect(result.language).toBe("python");
    expect(result.exitCode).toBe(0);
    expect(String(result.output)).toContain("report written");
  });

  it("reports unknown skills as errors", async () => {
    const tool = makeRunSkillCodeTool([PYTHON_SKILL], { runner: fakeRunner({}) });
    const result = (await tool.handler({ skill_id: "nope" })) as Record<string, unknown>;
    expect(result.ok).toBe(false);
    expect(String(result.error)).toContain("Unknown skill");
  });

  it("rejects unsupported skill languages honestly", async () => {
    const tool = makeRunSkillCodeTool(
      [{ id: "go1", name: "gopher", language: "Go", code: "package main" }],
      { runner: fakeRunner({}) },
    );
    const result = (await tool.handler({ skill_id: "go1" })) as Record<string, unknown>;
    expect(result.ok).toBe(false);
    expect(String(result.error)).toContain("unsupported language");
  });

  it("substitutes {{params}} into the executed code", async () => {
    let executed = "";
    // Python code ships via stdin (`python3 -`), so the fake runner must read
    // opts.stdin — not args — to see the executed program.
    const runner: Runner = async (_cmd, _args, opts) => {
      executed = String(opts.stdin ?? "");
      return { stdout: "ok", stderr: "", exitCode: 0, timedOut: false };
    };
    const tool = makeRunSkillCodeTool(
      [{ id: "p1", name: "printer", language: "Python", code: "print('{{who}}')" }],
      { runner },
    );
    await tool.handler({ skill_id: "p1", params: { who: "Nexus" } });
    expect(executed).toContain("Nexus");
  });

  it("surfaces failed runs as recoverable errors — never throws (fail → recover → continue)", async () => {
    const tool = makeRunSkillCodeTool([PYTHON_SKILL], {
      runner: fakeRunner({ stderr: "Traceback: boom", exitCode: 1 }),
    });
    const result = (await tool.handler({ skill_id: "skill-1" })) as Record<string, unknown>;
    expect(result.ok).toBe(false);
    expect(result.recoverable).toBe(true);
    expect(String(result.recoveryHint)).toContain("fix");
    // A throwing tool would kill the harness loop; this contract is the point.
    expect(async () => tool.handler({ skill_id: "skill-1" })).not.toThrow();
  });

  it("maps TypeScript skills to the tsx sandbox path", async () => {
    const tool = makeRunSkillCodeTool([TS_SKILL], { runner: fakeRunner({}) });
    const result = (await tool.handler({ skill_id: "skill-2" })) as Record<string, unknown>;
    expect(result.language).toBe("typescript");
  });
});

describe("skill-execution graph events (runtime-emitted, zero model writes)", () => {
  type CapturedSkillEvent = {
    skillId: string;
    skillName: string;
    status: "started" | "completed" | "failed";
    detail?: string;
    from?: string;
  };

  function collectingRecorder(): {
    recorder: SkillExecutionRecorder;
    events: CapturedSkillEvent[];
  } {
    const events: CapturedSkillEvent[] = [];
    return {
      recorder: {
        recordSkillExecution: (e) => {
          events.push(e);
          return `node-${events.length}`; // deterministic id for chaining assertions
        },
      },
      events,
    };
  }

  it("pre-execution emits started → completed per real run — nothing for non-runs", async () => {
    const { recorder, events } = collectingRecorder();
    const results = await executeSkillsOnce(
      [
        PYTHON_SKILL,
        TS_SKILL,
        { id: "go1", name: "gopher", language: "Go", code: "package main" },
        { id: "blank", name: "blank", language: "Python", code: "" },
      ],
      { runner: fakeRunner({ stdout: "ran", exitCode: 0 }), onExecution: recorder },
    );
    expect(results).toHaveLength(4); // unsupported + empty still return honest results
    expect(events.map((e) => e.status)).toEqual([
      "started",
      "completed",
      "started",
      "completed",
    ]);
    expect(events[0]!.skillId).toBe("skill-1");
    expect(events[0]!.skillName).toBe("report-writer");
    expect(events[1]!.from).toBe("node-1"); // terminal chains to its started node
    expect(events[1]!.detail).toContain("completed");
    expect(events[2]!.skillId).toBe("skill-2");
    expect(events[2]!.detail).toContain("typescript");
  });

  it("marks failed pre-executions as failed events with a short outcome", async () => {
    const { recorder, events } = collectingRecorder();
    await executeSkillsOnce([PYTHON_SKILL], {
      runner: fakeRunner({ stderr: "Traceback: boom", exitCode: 2 }),
      onExecution: recorder,
    });
    expect(events.map((e) => e.status)).toEqual(["started", "failed"]);
    expect(events[1]!.detail).toContain("failed");
    expect(events[1]!.detail).toContain("exit 2");
  });

  it("run_skill_code tool emits started → completed around a model-driven run", async () => {
    const { recorder, events } = collectingRecorder();
    const tool = makeRunSkillCodeTool([PYTHON_SKILL], {
      runner: fakeRunner({ stdout: "report written", exitCode: 0 }),
      onExecution: recorder,
    });
    const result = (await tool.handler({ skill_id: "skill-1" })) as Record<string, unknown>;
    expect(result.ok).toBe(true);
    expect(events.map((e) => e.status)).toEqual(["started", "completed"]);
    expect(events[0]!.skillName).toBe("report-writer");
    expect(events[0]!.detail).toContain("30000ms budget");
    expect(events[1]!.from).toBe("node-1");
    expect(events[1]!.detail).toContain("completed");
  });

  it("emits no skill events when the tool never runs a skill", async () => {
    const { recorder, events } = collectingRecorder();
    const tool = makeRunSkillCodeTool([PYTHON_SKILL], {
      runner: fakeRunner({}),
      onExecution: recorder,
    });
    await tool.handler({ skill_id: "nope" });
    await tool.handler({ skill_id: "go1" }); // not in this tool's skill set → unknown
    expect(events).toHaveLength(0);
  });
});