# SPDX-License-Identifier: Apache-2.0
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.secretName" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
