# SPDX-License-Identifier: Apache-2.0
{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}-api
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
---
{{- if .Values.ingest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}-ingest
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  type: {{ .Values.ingest.service.type }}
  ports:
    - port: {{ .Values.ingest.service.port }}
      targetPort: {{ .Values.ingest.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
{{- end }}
