# SPDX-License-Identifier: Apache-2.0
{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus.fullname" . }}-worker
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "nexus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.global.image.registry }}/{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexus.fullname" . }}-secrets
                  key: DATABASE_URL
            - name: NEXUS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexus.fullname" . }}-secrets
                  key: NEXUS_API_KEY
            - name: NEXUS_AUDIT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexus.fullname" . }}-secrets
                  key: NEXUS_AUDIT_KEY
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexus.fullname" . }}-secrets
                  key: GROQ_API_KEY
            - name: REDIS_URL
              value: {{ .Values.global.env.REDIS_URL | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.global.env.LOG_LEVEL | quote }}
          livenessProbe:
            exec:
              command: ["node", "-e", "process.exit(0)"]
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
