# SPDX-License-Identifier: Apache-2.0
{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus.fullname" . }}-worker
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "nexus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.global.image.registry }}/{{ .Values.worker.image.repository }}:{{ .Values.image.tag | default .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "nexus.fullname" . }}-config
            - secretRef:
                name: {{ include "nexus.secretName" . }}
          livenessProbe:
            exec:
              command: ["node", "-e", "process.exit(0)"]
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
