// SPDX-License-Identifier: Apache-2.0
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["tests/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      // Scope coverage to source TypeScript files only — this prevents
      // dist/ build artifacts and *.d.ts declaration files (generated by
      // pnpm build running before tests in CI) from polluting the report.
      include: ["src/**/*.ts"],
      // Exclude CLI entry points — command-dispatch shells requiring a live
      // runtime/terminal; covered by integration/e2e tests, not unit tests.
      exclude: ["src/index.ts", "src/runtime-cli.ts"],
      thresholds: {
        // Ratchet: raise by ~5 pts each sprint
        lines: 50,
        functions: 60,
        branches: 45,
        statements: 50,
      },
    },
  },
});
