// SPDX-License-Identifier: Apache-2.0
/**
 * Write openapi.yaml from the live Fastify route table.
 *
 *   pnpm openapi:generate   regenerate the file
 *   pnpm openapi:check      fail if the committed file is stale
 *
 * The spec used to be maintained by hand and covered 21 of roughly 850
 * registered operations. It is now an artefact: edit the routes, run this.
 *
 * Lives inside apps/api rather than in the repo-root scripts directory because
 * it imports the server, and the workspace packages only resolve from here.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { buildServer } from "../src/server.js";

// Booting the server starts stores that expect a reachable database, Redis and
// so on. The spec needs only the route table, so a background store that cannot
// connect must not abort generation — that would make the spec un-generatable
// anywhere except a fully provisioned machine.
process.on("unhandledRejection", (err: unknown) => {
  console.warn(`[generate-openapi] ignoring background failure: ${String(err)}`);
});

const repoRoot = resolve(fileURLToPath(import.meta.url), "../../../..");
const target = resolve(repoRoot, "openapi.yaml");
const checkOnly = process.argv.includes("--check");

const HEADER = [
  "# Generated by scripts/generate-openapi.ts from the live Fastify route table.",
  "# Do not edit by hand: run `pnpm openapi:generate` instead.",
  "",
].join("\n");

async function render(): Promise<string> {
  const app = await buildServer();
  await app.ready();
  try {
    return HEADER + app.swagger({ yaml: true });
  } finally {
    await app.close();
  }
}

async function main(): Promise<void> {
  const generated = await render();

  if (!checkOnly) {
    writeFileSync(target, generated, "utf8");
    console.log(`Wrote ${target}`);
    return;
  }

  let committed = "";
  try {
    committed = readFileSync(target, "utf8");
  } catch {
    console.error("openapi.yaml is missing. Run `pnpm openapi:generate`.");
    process.exitCode = 1;
    return;
  }
  // Normalise line endings: the file is generated on both Windows and Linux.
  const lf = (text: string) => text.split("\r\n").join("\n");
  if (lf(committed) !== lf(generated)) {
    console.error("openapi.yaml is out of sync with the routes. Run `pnpm openapi:generate`.");
    process.exitCode = 1;
    return;
  }
  console.log("openapi.yaml is in sync.");
}

// Not top-level await: this file is transpiled to CommonJS by tsx.
// The API keeps timers and pools alive, so exit explicitly once the work is done.
void main().then(
  () => process.exit(process.exitCode ?? 0),
  (err: unknown) => {
    console.error(err);
    process.exit(1);
  },
);
