// SPDX-License-Identifier: Apache-2.0
import { describe, it, expect } from "vitest";
import {
  DiscordRenderer,
  TelegramRenderer,
  HtmlRenderer,
  PlainRenderer,
  RendererRegistry,
  type MessagePayload,
} from "../src/index.js";

const basicPayload: MessagePayload = {
  text: "Hello **world**!",
};

const richPayload: MessagePayload = {
  text: "Report ready",
  embeds: [{
    title: "Status Update",
    description: "All systems operational",
    color: "#5865F2",
    fields: [
      { name: "Health", value: "OK", inline: true },
      { name: "Latency", value: "42ms" },
    ],
    footer: "Generated by Nexus",
    url: "https://example.com",
  }],
  table: {
    headers: ["Name", "Score"],
    rows: [["Alice", "95"], ["Bob", "87"]],
  },
  code: { language: "typescript", content: "const x = 42;" },
  attachments: ["report.pdf", "data.csv"],
};

// ── DiscordRenderer ───────────────────────────────────────────────────────────

describe("DiscordRenderer", () => {
  const renderer = new DiscordRenderer();

  it("renders plain text", () => {
    const r = renderer.render({ text: "Hello!" });
    expect(r.output).toContain("Hello!");
    expect(r.platform).toBe("discord");
    expect(r.truncated).toBe(false);
  });

  it("preserves bold markdown", () => {
    const r = renderer.render({ text: "Hello **world**" });
    expect(r.output).toContain("**world**");
  });

  it("renders code block", () => {
    const r = renderer.render({ code: { language: "ts", content: "const x = 1;" } });
    expect(r.output).toContain("```ts");
    expect(r.output).toContain("const x = 1;");
  });

  it("renders markdown table", () => {
    const r = renderer.render({ table: { headers: ["A", "B"], rows: [["1", "2"]] } });
    expect(r.output).toContain("| A");
    expect(r.output).toContain("| 1");
    expect(r.output).toContain("|--");
  });

  it("renders embed fields", () => {
    const r = renderer.render(richPayload);
    expect(r.output).toContain("**Status Update**");
    expect(r.output).toContain("**Health**: OK");
    expect(r.output).toContain("_Generated by Nexus_");
  });

  it("truncates at maxLength", () => {
    const r = new DiscordRenderer({ maxLength: 20 });
    const result = r.render({ text: "a".repeat(100) });
    expect(result.truncated).toBe(true);
    expect(result.output.length).toBeLessThanOrEqual(20);
    expect(result.output.endsWith("...")).toBe(true);
  });

  it("renders attachments", () => {
    const r = renderer.render({ attachments: ["file.pdf"] });
    expect(r.output).toContain("file.pdf");
  });
});

// ── TelegramRenderer ──────────────────────────────────────────────────────────

describe("TelegramRenderer", () => {
  const renderer = new TelegramRenderer();

  it("escapes special chars in MarkdownV2", () => {
    const r = renderer.render({ text: "Price: $10.99 (sale!)" });
    expect(r.output).not.toContain("$10.99 (sale!)"); // must be escaped
    expect(r.output).toContain("\\$10\\.99 \\(sale\\!\\)");
  });

  it("renders bold title in embed", () => {
    const r = renderer.render({ embeds: [{ title: "Update" }] });
    expect(r.output).toContain("*Update*");
  });

  it("renders code as fenced block", () => {
    const r = renderer.render({ code: { language: "py", content: "print('hi')" } });
    expect(r.output).toContain("```");
  });

  it("renders table as code block", () => {
    const r = renderer.render({ table: { headers: ["X"], rows: [["1"]] } });
    expect(r.output).toContain("```");
    expect(r.output).toContain("| X");
  });

  it("HTML parseMode skips escaping", () => {
    const r = new TelegramRenderer({ parseMode: "HTML" });
    const result = r.render({ text: "<b>bold</b>", code: { content: "x = 1" } });
    expect(result.output).toContain("&lt;b&gt;bold&lt;/b&gt;");
    expect(result.output).toContain("<pre><code>");
  });

  it("truncates at maxLength with escaped ellipsis", () => {
    const r = new TelegramRenderer({ maxLength: 20 });
    const result = r.render({ text: "x".repeat(200) });
    expect(result.truncated).toBe(true);
  });

  it("platform is telegram", () => {
    expect(renderer.render({}).platform).toBe("telegram");
  });
});

// ── HtmlRenderer ──────────────────────────────────────────────────────────────

describe("HtmlRenderer", () => {
  const renderer = new HtmlRenderer();

  it("escapes HTML entities in text", () => {
    const r = renderer.render({ text: "<script>alert('xss')</script>" });
    expect(r.output).not.toContain("<script>");
    expect(r.output).toContain("&lt;script&gt;");
  });

  it("converts **bold** to <strong>", () => {
    const r = renderer.render({ text: "Hello **world**!" });
    expect(r.output).toContain("<strong>world</strong>");
  });

  it("converts *italic* to <em>", () => {
    const r = renderer.render({ text: "Hello *world*!" });
    expect(r.output).toContain("<em>world</em>");
  });

  it("converts `code` to <code>", () => {
    const r = renderer.render({ text: "use `const`" });
    expect(r.output).toContain("<code>const</code>");
  });

  it("renders code block with language class", () => {
    const r = renderer.render({ code: { language: "typescript", content: "const x = 1;" } });
    expect(r.output).toContain('class="language-typescript"');
    expect(r.output).toContain("const x = 1;");
  });

  it("renders HTML table", () => {
    const r = renderer.render({ table: { headers: ["Name", "Val"], rows: [["Alice", "1"]] } });
    expect(r.output).toContain("<table>");
    expect(r.output).toContain("<th>Name</th>");
    expect(r.output).toContain("<td>Alice</td>");
  });

  it("renders embed with color border", () => {
    const r = renderer.render({ embeds: [{ title: "T", color: "#ff0000", description: "D" }] });
    expect(r.output).toContain("border-left: 4px solid #ff0000");
    expect(r.output).toContain("T");
  });

  it("renders embed URL as link", () => {
    const r = renderer.render({ embeds: [{ title: "Link", url: "https://example.com" }] });
    expect(r.output).toContain('<a href="https://example.com">Link</a>');
  });

  it("wrapBody option wraps in div.message", () => {
    const r = new HtmlRenderer({ wrapBody: true });
    const result = r.render({ text: "hi" });
    expect(result.output).toContain('<div class="message">');
  });

  it("platform is html", () => {
    expect(renderer.render({}).platform).toBe("html");
  });

  it("escapes attachment names", () => {
    const r = renderer.render({ attachments: ["<dangerous>.pdf"] });
    expect(r.output).not.toContain("<dangerous>");
    expect(r.output).toContain("&lt;dangerous&gt;");
  });
});

// ── PlainRenderer ─────────────────────────────────────────────────────────────

describe("PlainRenderer", () => {
  const renderer = new PlainRenderer();

  it("strips markdown asterisks", () => {
    const r = renderer.render({ text: "Hello **world** *italic*" });
    expect(r.output).not.toContain("**");
    expect(r.output).not.toContain("*");
    expect(r.output).toContain("Hello");
  });

  it("renders code as-is", () => {
    const r = renderer.render({ code: { content: "const x = 1;" } });
    expect(r.output).toContain("const x = 1;");
  });

  it("renders embed bracket title", () => {
    const r = renderer.render({ embeds: [{ title: "Status" }] });
    expect(r.output).toContain("[Status]");
  });

  it("never truncates", () => {
    const r = renderer.render({ text: "x".repeat(10_000) });
    expect(r.truncated).toBe(false);
  });
});

// ── RendererRegistry ──────────────────────────────────────────────────────────

describe("RendererRegistry", () => {
  it("createDefault registers all 4 platforms", () => {
    const reg = RendererRegistry.createDefault();
    expect(reg.platforms()).toContain("discord");
    expect(reg.platforms()).toContain("telegram");
    expect(reg.platforms()).toContain("html");
    expect(reg.platforms()).toContain("plain");
  });

  it("register supports chaining", () => {
    const reg = new RendererRegistry();
    expect(reg.register(new DiscordRenderer())).toBe(reg);
  });

  it("render dispatches to correct renderer", () => {
    const reg = RendererRegistry.createDefault();
    const r = reg.render("discord", { text: "hi" });
    expect(r.platform).toBe("discord");
  });

  it("render throws for unknown platform", () => {
    const reg = new RendererRegistry();
    expect(() => reg.render("discord", {})).toThrow("No renderer registered");
  });

  it("renderAll returns results for each platform", () => {
    const reg = RendererRegistry.createDefault();
    const results = reg.renderAll({ text: "test message" });
    expect(results.size).toBe(4);
    for (const [p, r] of results) {
      expect(r.platform).toBe(p);
    }
  });

  it("get returns registered renderer", () => {
    const reg = new RendererRegistry();
    const discord = new DiscordRenderer();
    reg.register(discord);
    expect(reg.get("discord")).toBe(discord);
    expect(reg.get("telegram")).toBeUndefined();
  });
});
